### ISSUE TITLE
重新 make 時可能產生的錯誤

### ISSUE THREAD

**Issue by caasi** [g0v/amis-moedict#3]
從 https://github.com/g0v/moedict-webkit/issues/215 搬過來的 issue ：

重編阿美語萌典時，遇到此錯誤：

```
fatal: destination path '../amis-safolu' already exists and is not an empty directory.
```

是否用某種方式提示開發者移除 `amis-safolu` 資料夾更友善？

**Comment by wildjcrt** [comment]
fixed by commit https://github.com/g0v/amis-moedict/commit/a7b2ad76c86d1a59dd2170d251ed8c05e7c93427
